### ISSUE TITLE
CLI is not working (v1.0.4)

### ISSUE THREAD

**Issue by BenjaOliva** [developer-sumit/react-native-lab#2]
**Issue:**

I followed the commands, checked the requirements and im getting this error:

<img width="945" alt="Captura de pantalla 2024-12-23 a la(s) 16 21 09" src="https://github.com/user-attachments/assets/5bf26f6a-7fd0-40b8-9fd6-88ffee8805f7" />

Here is my **Node** and **npm** versions:

- Node: v22.9.0
- npm: v10.8.3

**Comment by developer-sumit** [comment]
I am working on the new update. Give me some time and I will fix this with a new feature 😁

Thanks for using react-native-lab

**Comment by BenjaOliva** [comment]
> I am working on the new update. Give me some time and I will fix this with a new feature 😁
> 
> Thanks for using react-native-lab

No problem!

Btw, would be great to have some kind of Discord or way to contribute to this project if you are willing to

Thx in advance!

**Comment by developer-sumit** [comment]
Yeah sure 👍!
I was thinking the same but doubted that anyone would ever join it.

Use lowercase letters until I patch this.

**Comment by BenjaOliva** [comment]
> Yeah sure 👍!
> I was thinking the same but doubted that anyone would ever join it.
> 
> Use lowercase letters until I patch this.

Just tried with `challenge` on first CLI input step but same error.

**Comment by developer-sumit** [comment]
Check react-native-lab@1.1.0
Bug is fixed with a new feature included in it. Now you can use NativeWind.

Run the command
```bash
npx react-native-lab@latest
```
